name: Deploy Flutter Web to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Build Flutter Web
        run: flutter build web

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t $CONTAINER_IMAGE .
          docker push $CONTAINER_IMAGE

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Create Terraform state bucket if not exists
        run: |
          BUCKET_NAME="tf-state-$PROJECT_ID"
          if ! gsutil ls -b gs://$BUCKET_NAME >/dev/null 2>&1; then
            gsutil mb -p $PROJECT_ID -l $REGION gs://$BUCKET_NAME
            gsutil versioning set on gs://$BUCKET_NAME
          fi

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Apply Terraform Configuration
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="project_id=$PROJECT_ID" \
            -var="region=$REGION" \
            -var="container_image=$CONTAINER_IMAGE" \
            -var="domain_name=$DOMAIN_NAME"

# List of the variables used in the workflow:
# - GCP_PROJECT_ID: The Google Cloud project ID where the resources will be created.
# - GCP_REGION: The Google Cloud region where the resources will be created.
# - CONTAINER_IMAGE: The URI of the Docker image to be deployed.
# - DOMAIN_NAME: The domain name for the Cloud Run service.